### ISSUE TITLE
any progress about type safe of commit and dispatch

### ISSUE THREAD

**Issue by kaneruan** [ktsn/vuex-class#30] opened 2018-08-08 03:34 UTC

**Comment by OkanEsen** [comment] 2018-08-09 16:07
There is already an open issue for this: https://github.com/ktsn/vuex-class/issues/2

**Comment by ktsn** [comment] 2018-09-02 11:17
Duplicate of #2
See #16, https://github.com/vuejs/vuex/pull/1121

**Closed as completed by ktsn** 2018-09-02 11:17 UTC
