### ISSUE TITLE
@Getter Property 'xxx' has no initializer and is not definitely assigned in the constructor.

### ISSUE THREAD

**Issue by ziazon** [ktsn/vuex-class#19] opened 2018-03-13 14:51 UTC
when compiling I get the following:

```
36:50 Property 'visibility' has no initializer and is not definitely assigned in the constructor.
    35 |
  > 36 |     @Getter('visibility', { namespace }) private visibility: boolean;
       |                                                  ^
No lint errors found
Version: typescript 2.7.1, tslint 5.9.1
Time: 945ms
```

I looked at https://blogs.msdn.microsoft.com/typescript/2018/01/31/announcing-typescript-2-7/#stricter-class-property-checks but it wasn't any help here.  In practice (code), how can I resolve this so it builds?

**Comment by ktsn** [comment] 2018-03-13 14:53
Duplicate of #17 
Please add definite assignment assertion modifier.

```ts
@Getter('visibility', { namespace }) private visibility!: boolean;
```

**Closed as completed by ktsn** 2018-03-13 14:53 UTC
